# Generated by Django 5.0 on 2023-12-21 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'verbose_name_plural': 'Billing Addresses'},
        ),
    ]
